version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: totor
      MYSQL_USER: toto
      MYSQL_PASSWORD: tata
      MYSQL_DATABASE: titi
    volumes:
      - "./mysql_log.cnf:/etc/mysql/conf.d/mysql_log.cnf"
    ports:
      - "3307:3306"
  app:
    build: .
    environment:
      FLASK_ENV: 'development'
    ports:
      - "8001:5000"
    volumes:
      - ".:/app"



