db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: totor
    MYSQL_USER: toto
    MYSQL_PASSWORD: tata
    MYSQL_DATABASE: titi
app:
  build: .
  ports:
    - "8001:5000"
