"""Add smoker colum

Revision ID: 6f0aa2f7dbde
Revises: 9ff3a8d6555a
Create Date: 2022-05-26 16:41:13.492725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0aa2f7dbde'
down_revision = '9ff3a8d6555a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('smoker', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'smoker')
    # ### end Alembic commands ###
